# port: 9494
# socks-port: 9595
# mixed-port: 9696
redir-port: 9797
tproxy-port: 9898
mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
# info / warning / error / debug / silent
log-level: warning
ipv6: true
geodata-mode: true
geodata-loader: memconservative
external-controller: 0.0.0.0:9090 
external-controller-tls: 0.0.0.0:9091 # RESTful API HTTPS
# secret: "123456"
external-ui: ./dashboard/dist
tcp-concurrent: false
inbound-tfo: false
interface-name: ""
# routing-mark: 233
geox-url:
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
  geoip: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat"
  geosite: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat"
#  - always, Diaktifkan untuk memaksa semua proses agar cocok
#  - strict, Secara default, ini dinilai dari âˆšclash apakah diaktifkan atau tidak
#  - off, tidak cocok dengan prosesnya, disarankan untuk menggunakan mode ini di router
find-process-mode: off # always, strict, off
#  global-client-fingerprint:å…¨å±€TLSæŒ‡çº¹,ä¼˜å…ˆä½äºproxyå†…çš„ client-fingerprint
#  accepts "chrome","firefox","safari","ios","random","none" options.
#  Utls is currently support TLS transport in TCP/grpc/WS/HTTP for VLESS/Vmess and trojan.
# global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: false
experimental:
  sniff-tls-sni: false
  udp-fallback-match: false
  fingerprint: ""
sniffer:
  enable: false
  force-dns-mapping: false
  parse-pure-ip: false
  # Whether to use sniffing results as actual access, default false
  override-destination: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
    - '+.v2ex.com'
  skip-domain:
    - '+.google.com'
  sniffing:
    - tls
    - http
  port-whitelist:
    - "80"
    - "443"
tun:
  enable: false
  # biarkan default utun
  device: utun
  mtu: 9000
  # gvisor / lwip / system
  stack: system
  dns-hijack:
    - any:53
  auto-route: false
  auto-detect-interface: false
  inet4-address: 172.19.0.1/30
  inet6-address: [fdfe:dcba:9876::1/126]
  strict_route: false
  inet4_route_address:
    - 0.0.0.0/1
    - 128.0.0.0/1
  inet6_route_address:
    - "::/1"
    - "8000::/1"
  # include_android_user:
  # - 0
  # - 10
  # include_package:
  # - com.android.chrome
  # exclude_package:
  # - com.android.captiveportallogin
dns:
  enable: true
  ipv6: false
  prefer-h3: false
  default-nameserver:
    - '1.1.1.1'
    - '8.8.8.8'
  listen: 0.0.0.0:1053
  use-hosts: true
  # redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '+.lan'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
  nameserver:
    - '1.1.1.1'
    - 'tls://1.0.0.1:853'
    - '8.8.8.8'
    - 'tls://8.8.4.4:853'
    # - '127.0.0.1'
    # - 'tls://1.1.1.1:853' # DNS over TLS
    # - 'tls://1dot1dot1dot1.cloudflare-dns.com:853'
    # - dhcp://rmnet_data+ # dns from dhcp
    # - https://doh.pub/dns-query # DNS over HTTPS
    # - https://dns.alidns.com/dns-query#h3=true
    # - https://mozilla.cloudflare-dns.com/dns-query#clash&h3=true
  proxy-server-nameserver:
    - '1.1.1.1'
  # nameserver-policy:
    # '+.googlesyndication.com': 1.1.1.1
    # 'geosite:category-ads-all': 127.0.0.1
  # fallback:
    # - 'https://8.8.8.8/dns-query'
    # - 'tcp://8.8.4.4'
    # - 'quic://dns.adguard.com:784' # DNS over QUIC
  # fallback-filter:
    # geoip: false
    # geoip-code: 'ID'
    # geosite:
      # # - gfw
    # ipcidr:
      # # - 240.0.0.0/4
    # domain:
      # - '+.google.com'
      # - '+.facebook.com'
      # - '+.youtube.com'
      # - '+.github.com'
hosts:
  'ota.googlezip.net': 127.0.0.1
  'ota-cache1.googlezip.net': 127.0.0.1
  'ota-cache2.googlezip.net': 127.0.0.1
proxies:
# â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”[ SSH FILE PLACE ]â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
proxy-providers:
  CLASH:
    type: file
    path: ./assets/server/clash.yaml
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  OPOK:
    type: file
    path: ./assets/server/opok.yaml
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  LOADBALANCE:
    type: file
    path: ./assets/server/lb.yaml
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
  WIREGUARD:
    type: file
    path: ./assets/server/wireguard.yaml
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
# â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”[ GRUP ]â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
proxy-groups:
  - name: â­… ğŸŒ CENTER LINE ğŸŒ â­†
    type: select
    proxies: [DIRECT, REJECT, OPOK, NORMAL, BEST-PING, LOAD-BALANCE, BALANCE, WR]
  - name: OPOK
    type: select
    use: [OPOK]
  - name: NORMAL
    type: select
    use: [CLASH]
  - name: BEST-PING
    type: url-test
    url: http://cp.cloudflare.com/generate_204
    ninterval: 300
    tolerance: 50
    proxies: [DIRECT]
    use: [CLASH, OPOK]
    # â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”[LOAD-BALANCE]â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
  - name: LOAD-BALANCE
    type: load-balance
    use: [LOADBALANCE]
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: BALANCE
    type: load-balance
    proxies: [BALANCEÂ¹, BALANCEÂ²]
    interval: 300
  - name: BALANCEÂ¹
    type: select
    use: [OPOK, CLASH]
  - name: BALANCEÂ²
    type: select
    use: [CLASH, OPOK]
    # â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
  - name: WR
    type: select
    use: [WIREGUARD]
    # ------------------------------------------------{ RULE GRUP }------------------------------------------------
  - name: ADblock
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: Freefire
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: MLBB
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: Playstore
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: PUBG
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: Sosmed
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: Streaming
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: Tiktok
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: Whatsapp
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
  - name: Youtube
    type: select
    proxies: [DIRECT, REJECT, â­… ğŸŒ CENTER LINE ğŸŒ â­†]
# â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”[ RULE ]â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”â€”
rule-providers:
  block:
    type: http
    behavior: domain
    url: https://howdy.id/download/rules/clash.txt
    path: ./assets/rule/adblock.yaml
    interval: 86400
  Freefire:
    type: file
    behavior: classical
    path: "./assets/rule/Freefire.yaml"
  MLBB:
    type: file
    behavior: classical
    path: "./assets/rule/MLBB.yaml"
  Playstore:
    type: file
    behavior: classical
    path: "./assets/rule/Playstore.yaml"
  PUBG:
    type: file
    behavior: classical
    path: "./assets/rule/PUBG.yaml"   
  Sosmed:
    type: file
    behavior: classical
    path: "./assets/rule/Sosmed.yaml"
  Streaming:
    type: file
    behavior: classical
    path: "./assets/rule/Streaming.yaml"
  Tiktok:
    type: file
    behavior: classical
    path: "./assets/rule/Tiktok.yaml"
  Whatsapp:
    type: file
    behavior: classical
    path: "./assets/rule/Whatsapp.yaml"
  Youtube:
    type: file
    behavior: classical
    path: "./assets/rule/youtube.yaml"
rules:
  - RULE-SET,block,ADblock
  - RULE-SET,Freefire,Freefire
  - RULE-SET,MLBB,MLBB
  - RULE-SET,Playstore,Playstore
  - RULE-SET,PUBG,PUBG
  - RULE-SET,Sosmed,Sosmed
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Tiktok,Tiktok
  - RULE-SET,Whatsapp,Whatsapp
  - RULE-SET,Youtube,Youtube
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - MATCH,â­… ğŸŒ CENTER LINE ğŸŒ â­†
